export interface ExcelColumn {
  header: string;
  values: string[];
  /** Paralelo a values: true = esa celda va en ROJO (umbral de alerta). */
  alerts?: boolean[];
}

/**
 * Exporta un reporte profesional a Excel:
 * título, encabezados con fondo morado, autofiltro, bordes y anchos automáticos.
 * Recibe los valores YA resueltos (nombres, nunca IDs).
 */
export interface ExportOptions {
  /** Nombre de quien genera el reporte (se imprime en la cabecera). */
  generatedBy?: string;
  /**
   * Columnas numéricas que se marcan en rojo cuando el valor es <= 0
   * (p. ej. la diferencia de millaje de un camión pasado de mantenimiento).
   */
  alertWhenNotPositive?: string[];
}

export async function exportToExcel(
  title: string,
  columns: ExcelColumn[],
  options: ExportOptions = {},
): Promise<void> {
  return writeWorkbook(
    `${title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}`,
    [{ name: title, columns }],
    options,
  );
}

export interface ExcelSheet {
  name: string;
  columns: ExcelColumn[];
}

/** Nombre de hoja válido para Excel (máx. 31 caracteres, sin []:*?/\). */
function safeSheetName(name: string, index: number): string {
  const clean = name.replace(/[[\]:*?/\\]/g, ' ').trim();
  return (clean === '' ? `Sheet ${index + 1}` : clean).slice(0, 31);
}

/**
 * Libro de Excel con una hoja por reporte, con el mismo formato de marca.
 * Se usa para el paquete de reportes por rango de fechas del Dashboard.
 */
export async function exportWorkbook(fileName: string, sheets: ExcelSheet[]): Promise<void> {
  return writeWorkbook(fileName, sheets, {});
}

async function writeWorkbook(
  fileName: string,
  sheets: ExcelSheet[],
  options: ExportOptions = {},
): Promise<void> {
  // Carga diferida: ExcelJS solo se descarga cuando el usuario exporta.
  const [{ default: ExcelJS }, { saveAs }] = await Promise.all([
    import('exceljs'),
    import('file-saver'),
  ]);
  const workbook = new ExcelJS.Workbook();

  sheets.forEach((sheetSpec, sheetIndex) => {
  const title = sheetSpec.name;
  const columns = sheetSpec.columns;
  const sheet = workbook.addWorksheet(safeSheetName(title, sheetIndex));

  const colCount = columns.length;
  const rowCount = columns[0]?.values.length ?? 0;

  const titleRow = sheet.getRow(1);
  titleRow.getCell(1).value = title;
  titleRow.getCell(1).font = { name: 'Arial', size: 14, bold: true, color: { argb: 'FF2E6FDD' } };
  sheet.mergeCells(1, 1, 1, Math.max(colCount, 1));

  const dateRow = sheet.getRow(2);
  const stamp = new Date().toLocaleString('en-US', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  dateRow.getCell(1).value = options.generatedBy
    ? `Generated by ${options.generatedBy} · ${stamp}`
    : `Generated: ${stamp}`;
  dateRow.getCell(1).font = { name: 'Arial', size: 9, italic: true, color: { argb: 'FF6F6D7C' } };
  sheet.mergeCells(2, 1, 2, Math.max(colCount, 1));

  const headerRowIndex = 4;
  const headerRow = sheet.getRow(headerRowIndex);
  columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = col.header;
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF3E8BFF' } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.border = {
      top: { style: 'thin' },
      bottom: { style: 'thin' },
      left: { style: 'thin' },
      right: { style: 'thin' },
    };
  });

  const STATUS_COLORS: Record<string, string> = {
    OK: 'FF1E8E3E',
    ALERT: 'FFD93025',
    CAUTION: 'FFE8710A',
  };

  for (let r = 0; r < rowCount; r += 1) {
    const row = sheet.getRow(headerRowIndex + 1 + r);
    columns.forEach((col, c) => {
      const cell = row.getCell(c + 1);
      const value = col.values[r] ?? '';
      cell.value = value;
      const statusColor = STATUS_COLORS[value];
      // Alerta: la marca viene calculada con los umbrales configurados
      // (Alerts), o del modo heredado "<= 0 por encabezado".
      const numeric = Number(String(value).replace(/,/g, ''));
      const isAlert =
        col.alerts?.[r] === true ||
        ((options.alertWhenNotPositive ?? []).includes(col.header) &&
          value !== '' &&
          Number.isFinite(numeric) &&
          numeric <= 0);

      if (isAlert) {
        cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFD93025' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFDE7E6' } };
      } else {
        cell.font = statusColor
          ? { name: 'Arial', size: 10, bold: true, color: { argb: statusColor } }
          : { name: 'Arial', size: 10 };
      }
    });
  }

  // Ancho por columna: se ajusta al encabezado y al contenido más largo.
  columns.forEach((col, i) => {
    const longest = col.values.reduce((max, value) => Math.max(max, value.length), 0);
    const width = Math.max(col.header.length + 4, Math.min(longest + 3, 46), 9);
    sheet.getColumn(i + 1).width = width;
    sheet.getColumn(i + 1).alignment = { vertical: 'middle' };
  });

  if (rowCount > 0) {
    sheet.autoFilter = {
      from: { row: headerRowIndex, column: 1 },
      to: { row: headerRowIndex, column: colCount },
    };
  }
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  saveAs(blob, `${fileName.replace(/\s+/g, '_')}.xlsx`);
}

/** Letra de columna de Excel (1 -> A, 27 -> AA). */
function columnLetter(index: number): string {
  let n = index;
  let letters = '';
  while (n > 0) {
    const rem = (n - 1) % 26;
    letters = String.fromCharCode(65 + rem) + letters;
    n = Math.floor((n - 1) / 26);
  }
  return letters;
}

export interface TemplateField {
  label: string;
  required: boolean;
  type: string;
  /** Valores para lista desplegable (enums, SI/NO o nombres de catálogo). */
  options?: string[];
  /** Texto de ayuda para la hoja Guía. */
  hint: string;
}

const TEMPLATE_ROWS = 1000;

/**
 * Plantilla de captura en Excel: hoja "Plantilla" con encabezados de marca,
 * listas desplegables (enums, SI/NO y catálogos con sus nombres reales),
 * hoja "Guía" con el formato de cada columna y hoja "Listas" con los valores.
 */
export async function downloadExcelTemplate(
  title: string,
  fields: TemplateField[],
): Promise<void> {
  const [{ default: ExcelJS }, { saveAs }] = await Promise.all([
    import('exceljs'),
    import('file-saver'),
  ]);
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Template');
  const listsSheet = workbook.addWorksheet('Lists');
  const guideSheet = workbook.addWorksheet('Guide');

  // ===== Encabezados =====
  const headerRow = sheet.getRow(1);
  fields.forEach((field, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = field.required ? `${field.label} *` : field.label;
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF3E8BFF' } };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    sheet.getColumn(i + 1).width = Math.max(field.label.length + 4, 16);
  });
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  // ===== Listas desplegables =====
  let listColumn = 0;
  fields.forEach((field, i) => {
    if (!field.options || field.options.length === 0) return;
    listColumn += 1;
    const letter = columnLetter(listColumn);
    listsSheet.getCell(`${letter}1`).value = field.label;
    listsSheet.getCell(`${letter}1`).font = { name: 'Arial', size: 10, bold: true };
    field.options.forEach((option, j) => {
      listsSheet.getCell(`${letter}${j + 2}`).value = option;
    });
    listsSheet.getColumn(listColumn).width = 26;

    const targetLetter = columnLetter(i + 1);
    const range = `Listas!$${letter}$2:$${letter}$${field.options.length + 1}`;
    for (let row = 2; row <= TEMPLATE_ROWS; row += 1) {
      sheet.getCell(`${targetLetter}${row}`).dataValidation = {
        type: 'list',
        allowBlank: !field.required,
        formulae: [range],
        showErrorMessage: true,
        errorTitle: 'Invalid value',
        error: `Pick a value from the "${field.label}" list`,
      };
    }
  });

  // ===== Guía =====
  const guideHeader = guideSheet.getRow(1);
  ['Column', 'Required', 'Format / values'].forEach((label, i) => {
    const cell = guideHeader.getCell(i + 1);
    cell.value = label;
    cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF2E6FDD' } };
  });
  fields.forEach((field, i) => {
    const row = guideSheet.getRow(i + 2);
    row.getCell(1).value = field.label;
    row.getCell(2).value = field.required ? 'Yes' : 'No';
    row.getCell(3).value = field.hint;
    [1, 2, 3].forEach((c) => {
      row.getCell(c).font = { name: 'Arial', size: 10 };
    });
  });
  guideSheet.getColumn(1).width = 30;
  guideSheet.getColumn(2).width = 12;
  guideSheet.getColumn(3).width = 70;

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  saveAs(blob, `Plantilla_${title.replace(/\s+/g, '_')}.xlsx`);
}